# Generated by Django 5.1 on 2025-05-26 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landrecord',
            name='plot_details',
        ),
        migrations.AddField(
            model_name='landrecord',
            name='district',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='landrecord',
            name='plot_number',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='landrecord',
            name='region',
            field=models.CharField(default='Unkown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='landrecord',
            name='size',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='landrecord',
            name='title_deed_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='landrecord',
            name='digital_signature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='landrecord',
            name='issuer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='landrecord',
            name='record_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
