# Generated by Django 5.1 on 2025-05-26 19:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_remove_landrecord_plot_details_landrecord_district_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='landrecord',
            name='digital_signature',
            field=models.TextField(blank=True, default='N/A', null=True),
        ),
        migrations.AlterField(
            model_name='landrecord',
            name='district',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='landrecord',
            name='issuer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='landrecord',
            name='owner_id',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='landrecord',
            name='plot_number',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='landrecord',
            name='record_hash',
            field=models.CharField(default='N/A', max_length=64),
        ),
        migrations.AlterField(
            model_name='landrecord',
            name='region',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='landrecord',
            name='size',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='landrecord',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='landrecord',
            name='title_deed_number',
            field=models.CharField(blank=True, default='N/A', max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='landrecord',
            unique_together={('owner_id', 'plot_number', 'district', 'region', 'size', 'title_deed_number')},
        ),
    ]
